version: "3.8"
services:
  tender-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - POSTGRES_USER=ito21  # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
      - POSTGRES_PASSWORD=1899 # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
      - POSTGRES_DB=TENDER     # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - tender_network
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ito21   # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
      - POSTGRES_PASSWORD=1899 # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
      - POSTGRES_DB=TENDER    # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tender_network
networks:
  tender_network:
volumes:
    postgres_data: