version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tender_service
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Сохраняем данные базы данных между перезапусками

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tender_service
    depends_on:
      - db
    restart: unless-stopped # Автоматический перезапуск приложения в случае сбоя

volumes:
  db_data: # Определяем том для хранения данных базы данных
